#!/usr/bin/env python

from opsim4.cli_parser import create_parser

def main(options):
    import opsim4.config_ui
    opsim4.config_ui.run(options)

if __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()
    main(args)
