#!/usr/bin/env python

from opsim4.cli_parser import create_parser
from opsim4.widgets.config_ui import run

def main(options):
    run(options)

if __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()
    main(args)
